# -*- coding: utf-8 -*-

aws_ec2 = {'match_rules': {'1': ['reference.resource_id']},
 'resource': {'data': {'auto_scaling_group': {'arn': 'arn:aws:autoscaling:us-east-1:257706363616:autoScalingGroup:e276799f-54c4-4aa4-93f9-d5c5049cfc33:autoScalingGroupName/tf-asg-20200811081827368300000002',
                                              'launch_configuration': {'arn': 'arn:aws:autoscaling:us-east-1:257706363616:launchConfiguration:463182a6-17a8-452b-97cb-3f7ef72fedff:launchConfigurationName/terraform-20200811081812287400000001',
                                                                       'name': 'terraform-20200811081812287400000001'},
                                              'name': 'tf-asg-20200811081827368300000002'},
                       'aws': {'ebs_optimized': False,
                               'iam_instance_profile': None,
                               'lifecycle': 'scheduled',
                               'tags': [{'Key': 'Name',
                                         'Value': 'terraform-asg-example'},
                                        {'Key': 'aws:autoscaling:groupName',
                                         'Value': 'tf-asg-20200811081827368300000002'}]},
                       'cloudwatch': {'dimensions': [{'Name': 'InstanceId',
                                                      'Value': 'i-0547adda7071dcec7'}],
                                      'namespace': 'AWS/EC2',
                                      'region_name': 'us-east-1'},
                       'compute': {'account_id': '257706363616',
                                   'az': 'us-east-1d',
                                   'eip': [],
                                   'image': 'ubuntu/images/hvm-ssd/ubuntu-xenial-16.04-amd64-server-20161020',
                                   'instance_id': 'i-0547adda7071dcec7',
                                   'instance_name': 'terraform-asg-example',
                                   'instance_state': 'running',
                                   'instance_type': 't2.micro',
                                   'keypair': '',
                                   'launched_at': '2020-08-11T08:18:33.000000+0000',
                                   'region_name': 'us-east-1',
                                   'security_groups': ['terraform-example-instance'],
                                   'termination_protection': False},
                       'hardware': {'core': 1.0, 'memory': 1.0},
                       'load_balancers': [],
                       'os': {'details': '',
                              'os_arch': 'x86_64',
                              'os_distro': 'ubuntu'},
                       'public_dns': 'ec2-3-237-187-182.compute-1.amazonaws.com',
                       'public_ip_address': '3.237.187.182',
                       'security_group_rules': [{'description': '',
                                                 'direction': 'inbound',
                                                 'port': '8080',
                                                 'port_range_max': 8080.0,
                                                 'port_range_min': 8080.0,
                                                 'protocol': 'TCP',
                                                 'remote': '0.0.0.0/0',
                                                 'remote_cidr': '0.0.0.0/0',
                                                 'security_group_id': 'sg-0da0d035055c2a6c8',
                                                 'security_group_name': 'terraform-example-instance'}],
                       'subnet': {'cidr': '172.31.0.0/20',
                                  'subnet_arn': 'arn:aws:ec2:us-east-1:257706363616:subnet/subnet-90b442f6',
                                  'subnet_id': 'subnet-90b442f6',
                                  'subnet_name': ''},
                       'vpc': {'cidr': '172.31.0.0/16',
                               'vpc_arn': 'arn:aws:ec2:us-east-1:257706363616:vpc/vpc-3bbebd41',
                               'vpc_id': 'vpc-3bbebd41',
                               'vpc_name': ''}},
              'disks': [{'device': '/dev/sda1',
                         'device_index': 0.0,
                         'disk_type': 'EBS',
                         'size': 8.0,
                         'tags': {'encrypted': False,
                                  'iops': 100.0,
                                  'volume_id': 'vol-07d53a53a2f052cfe',
                                  'volume_type': 'gp2'}}],
              'ip_addresses': ['3.237.187.182', '172.31.4.44'],
              'metadata': {'view': {'sub_data': {'layouts': [{'name': 'AWS EC2',
                                                              'options': {'layouts': [{'name': 'EC2 '
                                                                                               'Instance',
                                                                                       'options': {'fields': [{'key': 'data.compute.instance_id',
                                                                                                               'name': 'Instance '
                                                                                                                       'ID',
                                                                                                               'type': 'text'},
                                                                                                              {'key': 'data.compute.instance_state',
                                                                                                               'name': 'Instance '
                                                                                                                       'State',
                                                                                                               'options': {'pending': {'options': {'icon': {'color': 'yellow.500'}},
                                                                                                                                       'type': 'state'},
                                                                                                                           'running': {'options': {'icon': {'color': 'green.500'}},
                                                                                                                                       'type': 'state'},
                                                                                                                           'shutting-down': {'options': {'icon': {'color': 'gray.400'},
                                                                                                                                                         'text_color': 'gray.400'},
                                                                                                                                             'type': 'state'},
                                                                                                                           'stopped': {'options': {'icon': {'color': 'red.500'},
                                                                                                                                                   'text_color': 'red.500'},
                                                                                                                                       'type': 'state'},
                                                                                                                           'stopping': {'options': {'icon': {'color': 'yellow.500'}},
                                                                                                                                        'type': 'state'}},
                                                                                                               'type': 'enum'},
                                                                                                              {'key': 'data.compute.instance_type',
                                                                                                               'name': 'Instance '
                                                                                                                       'Type',
                                                                                                               'type': 'text'},
                                                                                                              {'key': 'data.aws.lifecycle',
                                                                                                               'name': 'EC2 '
                                                                                                                       'Lifecycle',
                                                                                                               'options': {'scheduled': {'options': {'background_color': 'coral.600'},
                                                                                                                                         'type': 'badge'},
                                                                                                                           'spot': {'options': {'background_color': 'indigo.500'},
                                                                                                                                    'type': 'badge'}},
                                                                                                               'type': 'enum'},
                                                                                                              {'key': 'data.compute.keypair',
                                                                                                               'name': 'Key '
                                                                                                                       'Pair',
                                                                                                               'type': 'text'},
                                                                                                              {'key': 'data.aws.iam_instance_profile.arn',
                                                                                                               'name': 'IAM '
                                                                                                                       'Role '
                                                                                                                       'ARN',
                                                                                                               'type': 'text'},
                                                                                                              {'key': 'data.aws.ebs_optimized',
                                                                                                               'name': 'EBS-Optimized',
                                                                                                               'options': {'false': {'options': {'background_color': 'coral.600'},
                                                                                                                                     'type': 'badge'},
                                                                                                                           'true': {'options': {'background_color': 'indigo.500'},
                                                                                                                                    'type': 'badge'}},
                                                                                                               'type': 'enum'},
                                                                                                              {'key': 'data.compute.image',
                                                                                                               'name': 'AMI '
                                                                                                                       'ID',
                                                                                                               'type': 'text'},
                                                                                                              {'key': 'data.compute.region_name',
                                                                                                               'name': 'Region',
                                                                                                               'type': 'text'},
                                                                                                              {'key': 'data.compute.az',
                                                                                                               'name': 'Availability '
                                                                                                                       'Zone',
                                                                                                               'type': 'text'},
                                                                                                              {'key': 'data.compute.termination_protection',
                                                                                                               'name': 'Termination '
                                                                                                                       'Protection',
                                                                                                               'options': {'false': {'options': {'background_color': 'coral.600'},
                                                                                                                                     'type': 'badge'},
                                                                                                                           'true': {'options': {'background_color': 'indigo.500'},
                                                                                                                                    'type': 'badge'}},
                                                                                                               'type': 'enum'},
                                                                                                              {'key': 'data.public_dns',
                                                                                                               'name': 'Public '
                                                                                                                       'DNS',
                                                                                                               'type': 'text'},
                                                                                                              {'key': 'data.public_ip_address',
                                                                                                               'name': 'Public '
                                                                                                                       'IP',
                                                                                                               'type': 'text'},
                                                                                                              {'key': 'data.compute.eip',
                                                                                                               'name': 'Elastic '
                                                                                                                       'IPs',
                                                                                                               'options': {'delimiter': '<br>',
                                                                                                                           'item': {'options': {'outline_color': 'primary.500'},
                                                                                                                                    'type': 'badge'}},
                                                                                                               'type': 'list'},
                                                                                                              {'key': 'data.compute.security_groups',
                                                                                                               'name': 'Security '
                                                                                                                       'Groups',
                                                                                                               'options': {'delimiter': '<br>',
                                                                                                                           'item': {'options': {'outline_color': 'primary.500'},
                                                                                                                                    'type': 'badge'}},
                                                                                                               'type': 'list'},
                                                                                                              {'key': 'data.compute.account_id',
                                                                                                               'name': 'Account '
                                                                                                                       'ID',
                                                                                                               'type': 'text'},
                                                                                                              {'key': 'data.compute.launched_at',
                                                                                                               'name': 'Launched '
                                                                                                                       'At',
                                                                                                               'type': 'datetime'}]},
                                                                                       'type': 'item'},
                                                                                      {'name': 'VPC',
                                                                                       'options': {'fields': [{'key': 'data.vpc.vpc_id',
                                                                                                               'name': 'VPC '
                                                                                                                       'ID',
                                                                                                               'type': 'text'},
                                                                                                              {'key': 'data.vpc.vpc_name',
                                                                                                               'name': 'VPC '
                                                                                                                       'Name',
                                                                                                               'type': 'text'},
                                                                                                              {'key': 'data.subnet.subnet_id',
                                                                                                               'name': 'Subnet '
                                                                                                                       'ID',
                                                                                                               'type': 'text'},
                                                                                                              {'key': 'data.subnet.subnet_name',
                                                                                                               'name': 'Subnet '
                                                                                                                       'Name',
                                                                                                               'type': 'text'}]},
                                                                                       'type': 'item'},
                                                                                      {'name': 'Auto '
                                                                                               'Scaling '
                                                                                               'Group',
                                                                                       'options': {'fields': [{'key': 'data.auto_scaling_group.name',
                                                                                                               'name': 'Auto '
                                                                                                                       'Scaling '
                                                                                                                       'Group',
                                                                                                               'type': 'text'},
                                                                                                              {'key': 'data.auto_scaling_group.launch_configuration.name',
                                                                                                               'name': 'Launch '
                                                                                                                       'Configuration',
                                                                                                               'type': 'text'},
                                                                                                              {'key': 'data.auto_scaling_group.launch_template.name',
                                                                                                               'name': 'Launch '
                                                                                                                       'Template',
                                                                                                               'type': 'text'}]},
                                                                                       'type': 'item'}]},
                                                              'type': 'list'},
                                                             {'name': 'AWS '
                                                                      'Tags',
                                                              'options': {'fields': [{'key': 'Key',
                                                                                      'name': 'Key',
                                                                                      'type': 'text'},
                                                                                     {'key': 'Value',
                                                                                      'name': 'Value',
                                                                                      'type': 'text'}],
                                                                          'root_path': 'data.aws.tags'},
                                                              'type': 'table'},
                                                             {'name': 'Disk',
                                                              'options': {'fields': [{'key': 'device_index',
                                                                                      'name': 'Index',
                                                                                      'type': 'text'},
                                                                                     {'key': 'device',
                                                                                      'name': 'Name',
                                                                                      'type': 'text'},
                                                                                     {'key': 'size',
                                                                                      'name': 'Size(GiB)',
                                                                                      'type': 'text'},
                                                                                     {'key': 'tags.volume_id',
                                                                                      'name': 'Volume '
                                                                                              'ID',
                                                                                      'type': 'text'},
                                                                                     {'key': 'tags.volume_type',
                                                                                      'name': 'Volume '
                                                                                              'Type',
                                                                                      'options': {'gp2': {'options': {'outline_color': 'primary'},
                                                                                                          'type': 'badge'},
                                                                                                  'io1': {'options': {'outline_color': 'indigo.500'},
                                                                                                          'type': 'badge'},
                                                                                                  'sc1': {'options': {'outline_color': 'coral.600'},
                                                                                                          'type': 'badge'},
                                                                                                  'st1': {'options': {'outline_color': 'peacock.500'},
                                                                                                          'type': 'badge'},
                                                                                                  'standard': {'options': {'outline_color': 'green.500'},
                                                                                                               'type': 'badge'}},
                                                                                      'type': 'enum'},
                                                                                     {'key': 'tags.iops',
                                                                                      'name': 'IOPS',
                                                                                      'type': 'text'},
                                                                                     {'key': 'tags.encrypted',
                                                                                      'name': 'Encrypted',
                                                                                      'options': {'false': {'options': {'background_color': 'coral.600'},
                                                                                                            'type': 'badge'},
                                                                                                  'true': {'options': {'background_color': 'indigo.500'},
                                                                                                           'type': 'badge'}},
                                                                                      'type': 'enum'}],
                                                                          'root_path': 'disks'},
                                                              'type': 'table'},
                                                             {'name': 'NIC',
                                                              'options': {'fields': [{'key': 'device_index',
                                                                                      'name': 'Index',
                                                                                      'type': 'text'},
                                                                                     {'key': 'mac_address',
                                                                                      'name': 'MAC '
                                                                                              'Address',
                                                                                      'type': 'text'},
                                                                                     {'key': 'ip_addresses',
                                                                                      'name': 'IP '
                                                                                              'Addresses',
                                                                                      'options': {'delimiter': '<br>'},
                                                                                      'type': 'list'},
                                                                                     {'key': 'cidr',
                                                                                      'name': 'CIDR',
                                                                                      'type': 'text'},
                                                                                     {'key': 'public_ip_address',
                                                                                      'name': 'Public '
                                                                                              'IP',
                                                                                      'type': 'text'},
                                                                                     {'key': 'tags.public_dns',
                                                                                      'name': 'Public '
                                                                                              'DNS',
                                                                                      'type': 'text'}],
                                                                          'root_path': 'nics'},
                                                              'type': 'table'},
                                                             {'name': 'Security '
                                                                      'Groups',
                                                              'options': {'fields': [{'key': 'direction',
                                                                                      'name': 'Direction',
                                                                                      'options': {'inbound': {'options': {'background_color': 'indigo.500'},
                                                                                                              'type': 'badge'},
                                                                                                  'outbound': {'options': {'background_color': 'coral.600'},
                                                                                                               'type': 'badge'}},
                                                                                      'type': 'enum'},
                                                                                     {'key': 'security_group_name',
                                                                                      'name': 'Name',
                                                                                      'type': 'text'},
                                                                                     {'key': 'protocol',
                                                                                      'name': 'Protocol',
                                                                                      'options': {'ALL': {'options': {'outline_color': 'primary'},
                                                                                                          'type': 'badge'},
                                                                                                  'ICMP': {'options': {'outline_color': 'peacock.500'},
                                                                                                           'type': 'badge'},
                                                                                                  'TCP': {'options': {'outline_color': 'indigo.500'},
                                                                                                          'type': 'badge'},
                                                                                                  'UDP': {'options': {'outline_color': 'coral.600'},
                                                                                                          'type': 'badge'}},
                                                                                      'type': 'enum'},
                                                                                     {'key': 'port',
                                                                                      'name': 'Port '
                                                                                              'Rage',
                                                                                      'type': 'text'},
                                                                                     {'key': 'remote',
                                                                                      'name': 'Remote',
                                                                                      'type': 'text'},
                                                                                     {'key': 'description',
                                                                                      'name': 'Description',
                                                                                      'type': 'text'}],
                                                                          'root_path': 'data.security_group_rules'},
                                                              'type': 'table'},
                                                             {'name': 'ELB',
                                                              'options': {'fields': [{'key': 'name',
                                                                                      'name': 'Name',
                                                                                      'type': 'text'},
                                                                                     {'key': 'dns',
                                                                                      'name': 'DNS',
                                                                                      'type': 'text'},
                                                                                     {'key': 'type',
                                                                                      'name': 'Type',
                                                                                      'options': {'application': {'options': {'background_color': 'coral.600'},
                                                                                                                  'type': 'badge'},
                                                                                                  'network': {'options': {'background_color': 'indigo.500'},
                                                                                                              'type': 'badge'}},
                                                                                      'type': 'enum'},
                                                                                     {'key': 'protocol',
                                                                                      'name': 'Protocol',
                                                                                      'options': {'delimiter': '<br>'},
                                                                                      'type': 'list'},
                                                                                     {'key': 'port',
                                                                                      'name': 'Port',
                                                                                      'options': {'delimiter': '<br>'},
                                                                                      'type': 'list'},
                                                                                     {'key': 'scheme',
                                                                                      'name': 'Scheme',
                                                                                      'options': {'internal': {'options': {'background_color': 'coral.600'},
                                                                                                               'type': 'badge'},
                                                                                                  'internet-facing': {'options': {'background_color': 'indigo.500'},
                                                                                                                      'type': 'badge'}},
                                                                                      'type': 'enum'}],
                                                                          'root_path': 'data.load_balancers'},
                                                              'type': 'table'}]}}},
              'name': 'terraform-asg-example',
              'nics': [{'cidr': '172.31.0.0/20',
                        'device': '',
                        'device_index': 0.0,
                        'ip_addresses': ['172.31.4.44'],
                        'mac_address': '02:70:32:01:86:a9',
                        'nic_type': 'interface',
                        'public_ip_address': '3.237.187.182',
                        'tags': {'public_dns': 'ec2-3-237-187-182.compute-1.amazonaws.com'}}],
              'os_type': 'LINUX',
              'provider': 'aws',
              'reference': {'external_link': 'https://us-east-1.console.aws.amazon.com/ec2/v2/home?region=us-east-1#Instances:instanceId=i-0547adda7071dcec7',
                            'resource_id': 'arn:aws:ec2:us-east-1:257706363616:instance/i-0547adda7071dcec7'},
              'region_code': 'us-east-1',
              'region_type': 'AWS',
              'server_type': 'VM'},
 'resource_type': 'inventory.Server',
 'state': 'SUCCESS'}
